config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :blogs do
    resources :comments
    
    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
  
    collection do
      post :confirm
    end
  end

  root 'top#index'
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  resources :users, only: [:index, :show, :edit, :update] do
    resources :tasks
  end
  
  resources :relationships, only: [:create, :destroy]
  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :content, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
      if params[:back]
        @contact = Contact.new(contact_params)
      else
        @contact = Contact.new
      end
    end
    
    def create
      @contact = Contact.new(contact_params)
      if @contact.save
        redirect_to root_path, notice: "お問い合わせが完了しました！"
        NoticeMailer.sendmail_contact(@contact).deliver
      else
        render action: 'new'
      end
    end
    
    def confirm
      @contact = Contact.new(contact_params)
      render :new if @contact.invalid?
    end
    
    private
      def contact_params
        params.require(:contact).permit(:name, :email, :content)
      end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容でよろしいですか？</h3>
    <%= form_for(@contact) do |f| %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :content %>
      <p><%= @contact.name %></p>
      <p><%= @contact.email %></p>
      <p><%= @contact.content %></p>
      <%= f.submit "送信",class: 'btn btn-primary btn-block'%>
    <% end %>
    <%= form_for(@contact, url: new_contact_path, method: 'get')do |f|%>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :content %>
      <%= f.submit "戻る", name: 'back',class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>    
</div>

app/views/contacts/new.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
  <%= notice %>
  <h1>お問い合わせ内容を入力してください</h1>
    <%= form_for(@contact, url: confirm_contacts_path) do |f| %>
      <%= f.error_messages! %>
      
      <%= f.label :名前 %>
      <%= f.text_field :name, class: 'form-control' %>
      <br>
      <%= f.label :メールアドレス %>
      <%= f.text_field :email, class: 'form-control' %>
      <br>
      <%= f.label :内容 %>
      <%= f.text_field :content, class: 'form-control' %>
      <br>
      <%= f.submit "確認画面へ", class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>